<Project>
  <PropertyGroup>
    <NuGetAudit>false</NuGetAudit>
    <RestoreIgnoreFailedSources>true</RestoreIgnoreFailedSources>
    <!-- Ensures package restores generate Windows x64 and ARM64 assets for referenced projects. -->
    <RuntimeIdentifiers>win-x64;win-arm64</RuntimeIdentifiers>
  </PropertyGroup>
</Project>
